active_algo: UPP

algoDetails:
  - name: AStar
    args: {}
  - name: RRT
    args: {maxIter: 10000, goalSampleRate: 0.05, stepSize: 7, pointSamples: 100}
  - name: UPP
    args: {"alphaBase": 0.5,"betaBase": 10.0,"radiusBase": 1, "epsilon": 0.01,"betaMin": 0.1,"betaMax": 2.0,"betaDecay": 0.97,"betaRecovery": 1.05,"betaPatience": 20,"goalTol": 0.1,"alphaMin": 0.05,"alphaMax": 0.95,"alphaDecay": 0.97,"alphaRecovery": 1.05,"tolAngular": 180.0,"turnTarget": 15.0,"turnWindow": 10,"radiusMin": 1,"radiusMax": 5}
  - name: CBFRRT
    args: {maxIter: 10000, goalSampleRate: 0.05, stepSize: 7, pointSamples: 100, gamma1: 2, gamma2: 2}
  - name: FSPlanner
    args: {pointSamples: 100, cw: 1, epsilon: 0.01, maxNeigh: 5}
  - name: SDFAStar
    args: {k1: 5, k2: 5}
  - name: OptimizedAStar
    args: {turnPenaltyCoefficients: 0.5, safetyDistGridRadius: 100, maxInflateIter: 50, pointSamples: 100}
  - name: VoronoiPlanner
    args: {pointSamples: 100, knn: 100}
